package HelloModule;


/**
* HelloModule/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Sunday, 30 May, 2021 1:31:34 PM IST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
