package HelloModule;


/**
* HelloModule/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Sunday, 30 May, 2021 1:31:34 PM IST
*/

public interface HelloOperations 
{
  String print_hello (String s);
} // interface HelloOperations
