package HelloModule;

/**
* HelloModule/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Sunday, 30 May, 2021 1:31:34 PM IST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloModule.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (HelloModule.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloModule.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloModule.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloModule.HelloHelper.type ();
  }

}
